# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/workout_nb',
                'doc_host': 'https://dmose.github.io',
                'git_url': 'https://github.com/dmose/workout_nb',
                'lib_path': 'workout_nb'},
  'syms': {'workout_nb.core': {'workout_nb.core.foo': ('core.html#foo', 'workout_nb/core.py')}}}