# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_workout_nb.ipynb.

# %% auto 0
__all__ = ['Workout_NB']

# %% ../nbs/00_workout_nb.ipynb 3
class Workout_NB:
    "Create/use a workout tracking notebook"
    def __init__(self):
        print("stuff")

